### ISSUE TITLE
cannot find Basic_Map/capitals.RDS

### ISSUE THREAD

**Issue by ellisp** [expectopatronum/Maps_With_R_Leaflet#1]
Hi, after checking 'swirl' is up to date and installing the Maps_With_R_)Leaflet course and running it in swirl I get this error:

```
Error in gzfile(file, "rb") : cannot open the connection
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file 'Basic_Map/capitals.RDS', probable reason 'No such file or directory'

```

Here's my session info:

```
> sessionInfo()
R version 3.2.4 Revised (2016-03-16 r70336)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=English_New Zealand.1252  LC_CTYPE=English_New Zealand.1252   
[3] LC_MONETARY=English_New Zealand.1252 LC_NUMERIC=C                        
[5] LC_TIME=English_New Zealand.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] leaflet_1.0.1 yaml_2.1.13   swirl_2.4.0  

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.3     digest_0.6.9    crayon_1.3.1    bitops_1.0-6   
 [5] R6_2.1.2        magrittr_1.5    httr_1.1.0      stringi_1.0-1  
 [9] curl_0.9.6      testthat_0.11.0 tools_3.2.4     stringr_1.0.0  
[13] htmlwidgets_0.6 RCurl_1.95-4.8  memoise_1.0.0   htmltools_0.3.5
```

**Comment by expectopatronum** [comment]
Thank you for reporting this error! Since I tested my course in the same working directory as I developed it I didn't notice. The problem seems to be that the working directory is not the same as the course directory and therefore the path is not correct. I am talking to swirl about it right now. I am not sure right now how to include the data otherwise.

**Comment by expectopatronum** [comment]
Found a piece of code in https://github.com/swirldev/swirl_courses/blob/master/Exploratory_Data_Analysis/CaseStudy/initLesson.R to load data from the course directory.
Now the course also works from other directories as it should :)

`path_to_course <- file.path(find.package("swirl"),"Courses/Maps_With_R_Leaflet/Basic_Map/")
path_to_file <- "capitals.RDS"
data_file <- paste0(path_to_course, path_to_file)

capitals <- readRDS(data_file)
linz_lng <- capitals[capitals$GEMEINDE=="Linz", "LNG"]
linz_lat <- capitals[capitals$GEMEINDE=="Linz", "LAT"]`

**Comment by ellisp** [comment]
I still get the same error... do you get it working on a clean install, opening up a clean session like a new user would?

**Comment by expectopatronum** [comment]
It seems to work on Mac OS, but I also get the error on Windows. Which OS are you using?

It seems that this piece of code is not doing the same on all operating systems:

```
path_to_course <- file.path(find.package("swirl"),"Courses/Maps_With_R_Leaflet/Basic_Map/")
path_to_file <- "capitals.RDS"
data_file <- paste0(path_to_course, path_to_file)
capitals <- readRDS(data_file)
```

**Comment by expectopatronum** [comment]
I just noticed I misunderstood the meaning of the method `file.path`. I changed the code to:

```
path_to_course <- file.path(find.package("swirl"),"Courses/Maps_With_R_Leaflet/Basic_Map/", "capitals.RDS")
data_file <- path_to_course
capitals <- readRDS(data_file)
```

No it works on my Windows machine. Does it work for you? Thanks for your patience!

**Comment by ellisp** [comment]
Yes, it works now.  Thanks.
